sudo: required
services:
    - docker
    
before_install:
    - docker build -t varunsaraogi/docker-react -f Dockerfile.dev .

script:
    - docker run varunsaraogi/docker-react npm run test -- --coverage